name: Build for Linux

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install mingw-w64 libwavpack-dev libogg-dev libvorbis-dev libpthread-stubs0-dev libmpg123-dev libssl-dev

      - name: Build the project
        run: |
          cmake -B build -S .
          cmake --build build --config Release

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: build/TGControlPanel
