name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64

      - name: Install dependencies
        run: |
          ./vcpkg install sdl2:x64-windows
          ./vcpkg install sdl2-mixer:x64-windows
          ./vcpkg install tgbot-cpp:x64-windows

      - name: Build the project
        run: |
          cmake -Bbuild -S.
          cmake --build build --config Release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: build/TGControlPanel.exe
