name: Build with MinGW on Windows

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  

    - name: Install MinGW
      run: |
        choco install mingw  

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'  

    - name: Verify MinGW Installation
      run: |
        gcc --version  

    - name: Configure CMake project
      run: |
        cmake -G "MinGW Makefiles" -B build -S .  

    - name: Build project
      run: |
        cmake --build build --config Release  

    - name: Upload exe as artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyProjectExe
        path: build/MyProject.exe  
